@baseUrl = https://api.github.com
@token = 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
@acceptHeader = application/vnd.github.v3.html+json

GET {{baseUrl}}/user/starred
    ?page=1
Authorization: Bearer {{token}}
Accept: {{acceptHeader}}
If-None-Match: W/"d111cb77b9e69058dcf4ec1d01403f96c9889d3c6fe454e2dc1ffaf1147f1c48"

###
GET {{baseUrl}}/search/repositories
    ?q=flutter
    &page=1
Authorization: Bearer {{token}}
Accept: {{acceptHeader}}

###
GET {{baseUrl}}/repos/flutter/flutter/readme
Authorization: Bearer {{token}}
Accept: {{acceptHeader}}

###
PUT {{baseUrl}}/user/starred/flutter/flutter
Authorization: Bearer {{token}}
Accept: {{acceptHeader}}
Content-Length: 0

###
DELETE {{baseUrl}}/user/starred/flutter/flutter
Authorization: Bearer {{token}}
Accept: {{acceptHeader}}

###
GET {{baseUrl}}/user/starred/flutter/flutter
Authorization: Bearer {{token}}
Accept: {{acceptHeader}}